#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: microfab
  description: Microfab is a containerized Hyperledger Fabric runtime for use in development environments 
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
